name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12, 3.13]  # test multiple Python versions

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # 3️⃣ Create and activate venv, install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pillow flake8

    # 3️⃣ Black-line formatter
    - name: Check code style with Black
      run: |
        pip install black
        black --check .

    # 4️⃣ Run linter
    - name: Lint code with flake8
      run: |
        source venv/bin/activate
        flake8 . --exclude=venv,__pycache__
        
    # 5️⃣ Run tests
    - name: Run tests with pytest
      run: |
        source venv/bin/activate
        pytest -v
